### ISSUE TITLE
Opt out of food/transport for event

### ISSUE THREAD

**Issue by otytlandsvik** [td-org-uit-no/tdctl-frontend#124]
:sparkles: Change current opt-in for food and transport on events to opt-out instead. Most people choose them anyway.

:dizzy: Toggle buttons can be set to intially active when loading modal.

**Comment by FredrikMorstad** [comment]
I am not really sure this is a good idea as food and transportation are something that costs money and the user should make an active decision to get that service. I would rather have people not getting food because they didn't read the message than paying for something that was on by default.
