### ISSUE TITLE
Better formatting support for event descriptions

### ISSUE THREAD

**Issue by eliasriise** [td-org-uit-no/tdctl-frontend#129]
Add support for *this should be italic* (single star), **This should be bold** (double star), ***this should be both*** (triple star)

Add same for underline _italic_(single), __underlined_ (double), ____underline&italic___ (triple)

**Comment by eliasriise** [comment]
Maybe view this in RAW, to escape github formatting

**Comment by seblj** [comment]
For whoever tackles this issue: this looks like an interesting solution:

https://github.com/remarkjs/react-markdown
