### ISSUE TITLE
Add filter for people writing "None" in allegories field

### ISSUE THREAD

**Issue by Keyvan0111** [td-org-uit-no/tdctl-frontend#137]
Many are writing "none" or "ingen" etc. in allergier field. MAKE THEM STOP. 

Either don't allow them to type it.
 
OR MAKE THEM AT BOTTOM of list automatically, even after others sign up after them.

Please do this via a self trained language model.

Thank YOU

**Comment by otytlandsvik** [comment]
This issue has already been addressed with a toggle button to 'opt-in' to allergies. The text field on the modal is not available until this toggle is pressed.

Does the issue still persist? If so I agree it would be a good idea to filter these unnecessary inputs in post as proposed.

**Comment by otytlandsvik** [comment]
This seems to not be a problem anymore. Closing for now.
