### ISSUE TITLE
text length does not correspond to div width

### ISSUE THREAD

**Issue by Keyvan0111** [td-org-uit-no/tdctl-frontend#150]
text does not take div width into consideration

**Comment by FredrikMorstad** [comment]
Can you give an example so we can see the problem

**Comment by Keyvan0111** [comment]
> Can you give an example so we can see the problem

<img width="358" alt="Screenshot 2023-03-13 at 11 03 07" src="https://user-images.githubusercontent.com/111961782/224669877-9d78e861-2c8e-4404-b085-e2aed7da0c38.png">

**Comment by FredrikMorstad** [comment]
duplicate of #131
