### ISSUE TITLE
Let admins create their own toggle switches for events

### ISSUE THREAD

**Issue by eliasriise** [td-org-uit-no/tdctl-frontend#187]
Right now the only toggles available is food and transport, but if I want to make an event, let's say "Mario kart and smash tournament" I may want a switch that says "Jeg vil delta på smash" and one that  says "Jeg vil delta på Mario kart". NOT possible right now

**Comment by FredrikMorstad** [comment]
duplicate if #128

**Comment by eliasriise** [comment]
True, True....
