### ISSUE TITLE
Can't click links in event descriptions

### ISSUE THREAD

**Issue by eliasriise** [td-org-uit-no/tdctl-frontend#188]
![image](https://user-images.githubusercontent.com/43967847/236482310-3dd29279-292e-4fdc-b620-81c81105d2df.png)

Users should be able to just click the link

**Comment by eliasriise** [comment]
(they can't)

**Comment by FredrikMorstad** [comment]
Well markdown will only create a link if you follow the syntax. If you read the docs a link is only created if you follow the intended syntax `[placeholder](link)`
