### ISSUE TITLE
Pointer cursor on non-clickable object

### ISSUE THREAD

**Issue by Keyvan0111** [td-org-uit-no/tdctl-frontend#223]
Pointer on admin page for events. There is a orange calendar logo which is not clickable, however the cursor changes to a pointer.

Move cursor on the logo

Navigate to the admin page
click on events
Hover on the orange calendar symbol 
And BOOM!

Should stay as a cursor not turn into pointer

Screenshots hide cursor so sorry... You get no picture 😔

**Comment by otytlandsvik** [comment]
Picture of the symbol in table for reference :camera:  :
![image](https://github.com/td-org-uit-no/tdctl-frontend/assets/73795796/dbf4bd93-8d4a-4804-88df-1b0f8fb82be8)
