### ISSUE TITLE
TD LinkedIn in the footer

### ISSUE THREAD

**Issue by stiansolli** [td-org-uit-no/tdctl-frontend#257]
:sparkles: **Add TD´s LinkedIn to page footer**

:dizzy: **Explain your suggested solution**

TD has a LinkedIn account, this account should be linked with a logo along with TD´s other accounts at the bottom of the page.

![Skjermbilde 2024-02-29 kl  14 30 17](https://github.com/td-org-uit-no/tdctl-frontend/assets/77400647/b16b793e-c9e3-4a92-8165-2658642a769b)

**Comment by Keyvan0111** [comment]
Looks like this is done. Closing issue
