### ISSUE TITLE
Url for events should have eventname instead of ID

### ISSUE THREAD

**Issue by Keyvan0111** [td-org-uit-no/tdctl-frontend#297]
:sparkles: **What is your feature? Is it related to a problem?**

When looking at the url of an event page it looks something like this:
`https://td-uit.no/event/b0128b52-beb8-47d1-8d58-11b344020b13`

:dizzy: **Explain your suggested solution**

Perhaps use the title as the route name?

:twisted_rightwards_arrows: **Do you have some other alternative solutions?**

Add a field to the "Create event" where you write in one word what the event is and use this instead

:speech_balloon: **Additional thoughts**
N/A

**Comment by otytlandsvik** [comment]
This is possible, however we would need to
- Check the database to verify that this name is not taken
- Make sure two events do not share the same URL
- Somehow support both the legacy UUID and new naming system in the backend, or
- Keep the UUID and add the URL name as an additional field, in which case old events must also get this attribute

To me it seems to be slightly complex in return for not a lot of utility, that's my two cents. Feel free to reopen and argue for it if you still feel this could be useful and worth the effort.
