### ISSUE TITLE
Opening the website in a new tab requires another login 

### ISSUE THREAD

**Issue by eliasriise** [td-org-uit-no/tdctl-frontend#86]
Very annoying having to log in so often

**Comment by FredrikMorstad** [comment]
Session storage is only stored in one tab so the tokens storage system would need to be migrated to cookies or local storage.

**Comment by seblj** [comment]
+1 for httponly-cookie

**Comment by eliasriise** [comment]
EXCELLENT!!!!!!!

**Comment by seblj** [comment]
One small issue I found yesterday though, but that will be resolved by: https://github.com/td-org-uit-no/tdctl-api/pull/72
