### ISSUE TITLE
404 on event page on token timeout

### ISSUE THREAD

**Issue by otytlandsvik** [td-org-uit-no/tdctl-frontend#88]
:rotating_light: When refreshing event page after token timeout, "404 event not found" is displayed to the user, even though "401 unauthorized" is returned by the backend.

:mag: Reproduce:
- Go to an event page, logged in
- Wait for auth token to run out
- Refresh the site, or try to click "Meld på / Meld av"

:sparkles: Expected behavior:
User is redirected to login page, and event page is displayed again on login

**Comment by otytlandsvik** [comment]
Possibly duplicate of #83 🤔

**Comment by FredrikMorstad** [comment]
This is a design choice as all requests for an event a non-auth or auth user  does not have access to is will recieve a 404 page. So its caused by #83
