### ISSUE TITLE
Display event registration input to users after registration

### ISSUE THREAD

**Issue by otytlandsvik** [td-org-uit-no/tdctl-frontend#90]
## Task
  - Create a page showing all events the users is joined and add the following functionality:
    - Display: Title, date and preferences.
    - Add possibility to change food, transport and allergy 

## Original issue:
:sparkles: Display the information users entered to an event registration on the respective event page. 

Several people seemed to miss the buttons for transport and food when applying to Egde event, probably because people respond in a hurry to get a spot. Also, users might want to change their preferences after registering.

:dizzy: List the options for food, transport and allergies they entered, so they may take action if a mistake was made. A link to contact event responsible may be supplied here. This should not incentivize unnecessary response changes, but still provide the option if a mistake was made.

:twisted_rightwards_arrows: Alternatively, send email to participants listing their selected preferences.

**Comment by FredrikMorstad** [comment]
Good idea👍 I think a page like "upcoming events" where all events a users is joined is displayed would solve this. Here the user can see and change their preferences

**Comment by seblj** [comment]
> Good idea👍 I think a page like "upcoming events" where all events a users is joined is displayed would solve this. Here the user can see and change their preferences

We should however also probably limit when the user can change their preferences depending on how long before an event? Just commenting here so that it's something that we can remember (if you haven't already thought about that)
