### ISSUE TITLE
Add link to TD calendar at bottom of website

### ISSUE THREAD

**Issue by eliasriise** [td-org-uit-no/tdctl-frontend#92]
We gotta spread the word about the calendar!

**Comment by FredrikMorstad** [comment]
agreed, any suggestion as to where it should be placed? in the footer?

**Comment by eliasriise** [comment]
Yes, I think the footer is good, but I also created a document on google drive on how to add the calendar to your own Outlook https://docs.google.com/document/d/1iKERJJ3cHtAFaDcLyCXbGTgt3v1TFXggBv2uTbCqWCs/edit
